{
    "holdings": [
        [
            [
                "BEPL.NS",
                5000,
                103.55
            ]
        ],
        [
            [
                "EDELWEISS.NS",
                10000,
                80.0
            ]
        ],
        [
            [
                "BIOCON.NS",
                2000,
                65.3
            ]
        ]
    ],
    "target_profit": [
        [
            100000,
            -35000
        ],
        [
            160000,
            -60000
        ]
    ],
    "target_stocks": [
        [
            "BEPL.NS",
            98,
            1
        ],
        [
            "EDELWEISS.NS",
            76,
            1
        ],
        [
            "BEPL.NS",
            120,
            0
        ],
        [
            "EDELWEISS.NS",
            97,
            0
        ],
        [
            "BIOCON.NS",
            64.0,
            1
        ],
        [
            "BIOCON.NS",
            96.0,
            0
        ]
    ],
    "new_plan": [
        [
            [
                "ASHOKLEY",
                130,
                "26-May-2022",
                "PE",
                -9000
            ],
            [
                "ASHOKLEY",
                127.5,
                "26-May-2022",
                "PE",
                9000
            ]
        ]
    ]
}